### ISSUE TITLE
No LICENSE is specified

### ISSUE THREAD

**Issue by NoetherEmmy** [crumblingstatue/NoLifeExplorer#4]
Is this intentional? I'd like to create something like this and it would be great to use this project as a reference, but I'm worried that it is totally copyrighted and nonfree as a result of not having a license specified.

Ideally it could be licensed under the AGPL version 3+, to match with the rest of the NoLifeDev/NoLifeStory stuff. That would be greatly appreciated on behalf of the LibreMaple project (and anyone else who might want to use the software).

Thanks for your consideration.

**Comment by retep998** [comment]
This project uses [NoLifeNx](https://github.com/NoLifeDev/NoLifeStory) so technically this project would have to be licensed under GPL.

**Comment by NoetherEmmy** [comment]
I suppose that figures it then.

**Comment by retep998** [comment]
Still would be nice for @crumblingstatue to explicitly state the license though.

**Comment by crumblingstatue** [comment]
I'm usually too lazy to add a license to my projects, but if explicitly requested, I'll do it I guess.

**Comment by crumblingstatue** [comment]
Does https://github.com/crumblingstatue/NoLifeExplorer/commit/e839140577239cc4715d6a693b71c2abe1948ec4 suffice?

**Comment by NoetherEmmy** [comment]
Looks good to me.
